In [3]:
%reload_ext autoreload
%autoreload 2

%matplotlib inline

In [6]:
from dataset import *
from model import *

In [9]:
train_dl = DataLoader(train_ds, batch_size=4, shuffle=False)
xb, yb = next(iter(train_dl))

In [11]:
xb.shape, yb

(torch.Size([4, 3, 64, 64]), tensor([3, 1, 2, 1]))

In [27]:
net = SentinelNet([3, 16, 32], 5)

In [28]:
net

SentinelNet(
  (layers): ModuleList(
    (0): ConvBlock(
      (conv): Conv2d(3, 16, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
      (bn): BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (1): ConvBlock(
      (conv): Conv2d(16, 32, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
      (bn): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
  )
  (flatten): Lambda()
  (linear): Linear(in_features=32, out_features=5, bias=True)
)

In [38]:
out = net(xb)

> /home/srm/Desktop/current/quality-of-life/nbs/model.py(37)forward()
-> for layer in self.layers:
(Pdb) c


In [30]:
out.shape

torch.Size([4, 5])

In [33]:
torch.max(out, dim=1)

torch.return_types.max(
values=tensor([0.3646, 0.3071, 0.4829, 0.3248], grad_fn=<MaxBackward0>),
indices=tensor([0, 4, 3, 1]))

In [36]:
out = F.cross_entropy(out, yb)

In [37]:
out

tensor(1.5986, grad_fn=<NllLossBackward>)

In [39]:
out

tensor([[ 0.3646, -0.1119,  0.0792,  0.3170, -0.2526],
        [-0.0956, -0.3958,  0.1009, -0.2000,  0.3071],
        [ 0.2254, -0.4474, -0.0086,  0.4829, -0.3027],
        [-0.0186,  0.3248, -0.2655,  0.0557,  0.1433]],
       grad_fn=<AddmmBackward>)

In [40]:
yb

tensor([3, 1, 2, 1])

In [41]:
score, pred = torch.max(out, dim=1)
pred

tensor([0, 4, 3, 1])

In [44]:
(pred == yb).sum()

tensor(1)